name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Smart Contract Tests
  move-contracts:
    name: Move Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Sui CLI
        run: |
          wget -q https://github.com/MystenLabs/sui/releases/download/testnet-v1.58.1/sui-testnet-v1.58.1-ubuntu-x86_64.tgz
          tar -xzf sui-testnet-v1.58.1-ubuntu-x86_64.tgz
          sudo mv sui /usr/local/bin/
      
      - name: Build Move Contracts
        run: |
          cd contracts/manus_liquidity
          sui move build
      
      - name: Test Move Contracts
        run: |
          cd contracts/manus_liquidity
          sui move test

  # Backend Tests
  backend:
    name: Backend (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: backend/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Check formatting
        run: |
          cd backend
          cargo fmt -- --check
      
      - name: Run clippy
        run: |
          cd backend
          cargo clippy -- -D warnings
      
      - name: Run tests
        run: |
          cd backend
          cargo test --all-features
      
      - name: Build release
        run: |
          cd backend
          cargo build --release

  # Frontend Tests
  frontend:
    name: Frontend (Rust WASM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          targets: wasm32-unknown-unknown
      
      - name: Install Trunk
        run: cargo install --locked trunk
      
      - name: Build frontend
        run: |
          cd frontend
          trunk build --release
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/

  # Security Audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - name: Run cargo audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # Deploy (only on main branch)
  deploy:
    name: Deploy
    needs: [move-contracts, backend, frontend, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: manus-liquidity
          directory: frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

